### ISSUE TITLE
Empty bag

### ISSUE THREAD

**Issue by chelaxe** [DLzer/Zork#1]
https://github.com/DLzer/Zork/blob/6f61e0953e55e9b406b3f3db8926e1c8187c9768/assets/js/game.js#L399

change to:

`if(player.inventory === undefined || player.inventory.length == 0) {`

**Comment by DLzer** [comment]
👍 This will be implemented on version 2 of this Zork repo. You can see the progress on the `feat/GameEngine` branch.

**Comment by DLzer** [comment]
This is fixed in the beta release [v0.9.1-beta](https://github.com/DLzer/Zork/releases).
